site_name: Jayant Nehra
site_description: Developer, learner, writer
site_author: Jayant Nehra
site_url: https://Jay-Nehra.github.io/

# Repository
repo_url: https://github.com/Jay-Nehra/Jay-Nehra.github.io
repo_name: Jay-Nehra.github.io
edit_uri: edit/main/docs/

theme:
  name: material

  # Four deliberate reading modes
  palette:
    - scheme: parchment
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to warm parchment
  
    - scheme: parchment-warm
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-5
        name: Switch to solarized
  
    - scheme: solarized-teal
      primary: custom
      accent: custom
      toggle:
        icon: material/waves
        name: Switch to dark
  
    - scheme: ink-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to parchment
  

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.tabs.link

  font:
    text: Inter
    code: JetBrains Mono

# Navigation: Auto-generated by awesome-pages plugin
# Use .pages files in directories to customize order/titles

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - pymdownx.magiclink

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags
  - awesome-pages:
      collapse_single_pages: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true

extra_css:
  - stylesheets/custom.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jay-Nehra
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jayant-nehra

copyright: Copyright Â© 2026 Jayant Nehra
